"""Peptacular: a ProForma 2.1 peptide sequence parser and annotation library.

Everything listed in ``__all__`` is the public API and is importable from the top-level
package (``import peptacular as pt``). Reference data (modification, element, amino-acid
and protease lookups) belongs to :mod:`tacular`; only the tacular enums that peptacular
functions take as arguments (``IonType``, ``Protease``, ``NeutralDelta``) are re-exported.
"""

from tacular import IonType, NeutralDelta, Protease

from .annotation import AnnotationProperties, Fragment, Interval, Mod, Mods, ProFormaAnnotation
from .batch import BatchOperation, BatchResult, batch, diagnose, iter_batch
from .chem import chem_comp, chem_formula, chem_mass, parse_formula
from .constants import (
    C13_NEUTRON_MASS,
    CV,
    ELECTRON_MASS,
    NEUTRON_MASS,
    PEPTIDE_AVERAGINE_NEUTRON_MASS,
    PROTON_CARRIER_MASS,
    PROTON_MASS,
    ModType,
    ModTypeLiteral,
    ParallelMethod,
    ParallelMethodLiteral,
    Terminal,
)
from .diagnostics import (
    CompositionError,
    Diagnostic,
    InvalidAdjustmentError,
    InvalidPositionError,
    PeptacularError,
    PeptacularKeyError,
    ProFormaFormatError,
    UnknownElementError,
    UnknownEnzymeError,
    UnknownModificationError,
    UnsupportedOperationError,
)
from .digestion import DigestProtocol, EnzymeConfig
from .isotope import (
    AVERAGINE_RATIOS,
    IsotopicData,
    averagine_comp,
    brain_isotopic_distribution,
    estimate_averagine_comp,
    estimate_isotopic_distribution,
    merge_isotopic_distributions,
)
from .proforma_components import (
    ChargedFormula,
    ComkpTag,
    CompoundPeptidoformIon,
    ComupTag,
    FixedModification,
    FormulaElement,
    GlobalChargeCarrier,
    GlycanComponent,
    GlycanTag,
    IsotopeReplacement,
    LimitTag,
    ModificationAmbiguousPrimary,
    ModificationAmbiguousSecondary,
    ModificationCrossLinker,
    ModificationTags,
    Peptidoform,
    PeptidoformIon,
    PositionRule,
    PositionScore,
    PositionTag,
    SequenceElement,
    SequenceRegion,
    TagAccession,
    TagCustom,
    TagInfo,
    TagMass,
    TagName,
    add_composition,
    merge_compositions,
)
from .proforma_json import (
    PROFORMA_JSON_SCHEMA_ID,
    PROFORMA_JSON_SCHEMA_VERSION,
    from_proforma_dict,
    from_proforma_json,
    get_proforma_json_schema,
    to_proforma_dict,
    to_proforma_json,
)
from .property import (
    COMPOSITION_SCALES,
    FLEXIBILITY_SCALES,
    HPLC_SCALES,
    HYDROPHILICITY_SCALES,
    HYDROPHOBICITY_SCALES,
    PHYSICAL_PROPERTY_SCALES,
    POLARITY_SCALES,
    PROPERTY_SCALES,
    SURFACE_ACCESSIBILITY_SCALES,
    AggregationMethod,
    AggregationMethodLiteral,
    BetaStrandScale,
    ChargeScale,
    CompositionScale,
    HPLCScale,
    HydrophobicityScale,
    MissingAAHandling,
    MissingAAHandlingLiteral,
    PhysicalPropertyScale,
    PolarityScale,
    PropertyScale,
    SecondaryStructureMethod,
    SecondaryStructureScale,
    SecondaryStructureType,
    SurfaceAccessibilityScale,
    WeightingMethods,
    WeightingMethodsLiteral,
)
from .sequence import (
    DEFAULT_MAX_ISOMERS,
    DIGEST_RECORD_KEYS,
    FRAGMENT_RECORD_KEYS,
    aa_property_percentage,
    alpha_helix_percent,
    annotate_ambiguity,
    append_mods,
    aromaticity,
    average_buried_area,
    beta_sheet_percent,
    beta_turn_percent,
    bulkiness,
    calc_property,
    calc_window_property,
    candidate_sites,
    charge_at_ph,
    cleavage_sites,
    codons,
    coil_percent,
    combinations,
    combinations_with_replacement,
    comp,
    condense_static_mods,
    condense_to_peptidoform,
    convert_casanovo_sequence,
    convert_diann_sequence,
    convert_ip2_sequence,
    count_residues,
    coverage,
    digest,
    digest_records,
    extend_mods,
    fast_fragment,
    filter_mods,
    find_subsequence_indices,
    flexibility,
    frag,
    fragment,
    fragment_records,
    from_ms2_pip,
    generate_random,
    get_available_start_methods,
    get_mods,
    get_start_method,
    hplc,
    hydrophilicity,
    hydrophobicity,
    is_ambiguous,
    is_modified,
    is_subsequence,
    isotopic_distribution,
    join,
    left_semi_digest,
    localization_isomers,
    mass,
    modification_coverage,
    modify,
    mutability,
    mz,
    nonspecific_digest,
    pairwise_site_determining_ions,
    parse,
    parse_chimeric,
    percent_coverage,
    percent_residues,
    permutations,
    pi,
    polarity,
    pop_mods,
    product,
    property_partitions,
    recognition_factors,
    refractivity,
    remove_mods,
    reverse,
    right_semi_digest,
    secondary_structure,
    semi_digest,
    sequence_length,
    serialize,
    serialize_chimeric,
    set_mods,
    set_start_method,
    shift,
    shuffle,
    simple_cleavage_sites,
    simple_digest,
    site_determining_ions,
    sort,
    span_to_sequence,
    split,
    strip_mods,
    surface_accessibility,
    to_ms2_pip,
    transmembrane_tendency,
    validate,
)
from .sequence.util import HasSequence
from .spans import (
    Span,
    build_enzymatic_spans,
    build_left_semi_spans,
    build_non_enzymatic_spans,
    build_right_semi_spans,
    build_semi_spans,
    build_spans,
    calculate_span_coverage,
)
from .utils import get_mod_type

__version__ = "4.2.0"

__all__ = [
    "__version__",
    # tacular enums used as arguments
    "IonType",
    "NeutralDelta",
    "Protease",
    # annotation (OOP API)
    "ProFormaAnnotation",
    "AnnotationProperties",
    "Fragment",
    "Interval",
    "Mod",
    "Mods",
    # parse / serialize / validate
    "parse",
    "parse_chimeric",
    "serialize",
    "serialize_chimeric",
    "validate",
    "join",
    "split",
    # mass, m/z, composition
    "mass",
    "mz",
    "comp",
    "chem_mass",
    "chem_comp",
    "chem_formula",
    "parse_formula",
    "add_composition",
    "merge_compositions",
    # fragments
    "fragment",
    "frag",
    "fast_fragment",
    # localization
    "localization_isomers",
    "DEFAULT_MAX_ISOMERS",
    "candidate_sites",
    "site_determining_ions",
    "pairwise_site_determining_ions",
    # records (plain dicts for pandas/polars)
    "digest_records",
    "fragment_records",
    "DIGEST_RECORD_KEYS",
    "FRAGMENT_RECORD_KEYS",
    # digestion
    "digest",
    "simple_digest",
    "semi_digest",
    "left_semi_digest",
    "right_semi_digest",
    "nonspecific_digest",
    "cleavage_sites",
    "simple_cleavage_sites",
    "EnzymeConfig",
    "DigestProtocol",
    "Span",
    "build_spans",
    "build_enzymatic_spans",
    "build_semi_spans",
    "build_left_semi_spans",
    "build_right_semi_spans",
    "build_non_enzymatic_spans",
    "calculate_span_coverage",
    "span_to_sequence",
    # isotopes
    "isotopic_distribution",
    "brain_isotopic_distribution",
    "estimate_isotopic_distribution",
    "merge_isotopic_distributions",
    "averagine_comp",
    "estimate_averagine_comp",
    "IsotopicData",
    "AVERAGINE_RATIOS",
    # modifications
    "modify",
    "get_mods",
    "set_mods",
    "append_mods",
    "extend_mods",
    "pop_mods",
    "remove_mods",
    "filter_mods",
    "strip_mods",
    "condense_static_mods",
    "condense_to_peptidoform",
    "is_modified",
    "get_mod_type",
    "ModType",
    "ModTypeLiteral",
    # sequence utilities
    "sequence_length",
    "count_residues",
    "percent_residues",
    "is_ambiguous",
    "annotate_ambiguity",
    "generate_random",
    "reverse",
    "shift",
    "shuffle",
    "sort",
    "permutations",
    "combinations",
    "combinations_with_replacement",
    "product",
    "coverage",
    "percent_coverage",
    "modification_coverage",
    "find_subsequence_indices",
    "is_subsequence",
    # properties
    "calc_property",
    "calc_window_property",
    "hydrophobicity",
    "hydrophilicity",
    "flexibility",
    "surface_accessibility",
    "polarity",
    "mutability",
    "codons",
    "bulkiness",
    "recognition_factors",
    "transmembrane_tendency",
    "average_buried_area",
    "hplc",
    "refractivity",
    "charge_at_ph",
    "pi",
    "aa_property_percentage",
    "aromaticity",
    "secondary_structure",
    "alpha_helix_percent",
    "beta_sheet_percent",
    "beta_turn_percent",
    "coil_percent",
    "property_partitions",
    "PropertyScale",
    "HydrophobicityScale",
    "SecondaryStructureMethod",
    "SecondaryStructureScale",
    "SecondaryStructureType",
    "SurfaceAccessibilityScale",
    "ChargeScale",
    "PolarityScale",
    "HPLCScale",
    "BetaStrandScale",
    "PhysicalPropertyScale",
    "CompositionScale",
    "PROPERTY_SCALES",
    "HYDROPHOBICITY_SCALES",
    "SURFACE_ACCESSIBILITY_SCALES",
    "HPLC_SCALES",
    "HYDROPHILICITY_SCALES",
    "FLEXIBILITY_SCALES",
    "POLARITY_SCALES",
    "COMPOSITION_SCALES",
    "PHYSICAL_PROPERTY_SCALES",
    "MissingAAHandling",
    "MissingAAHandlingLiteral",
    "AggregationMethod",
    "AggregationMethodLiteral",
    "WeightingMethods",
    "WeightingMethodsLiteral",
    # converters
    "convert_ip2_sequence",
    "convert_diann_sequence",
    "convert_casanovo_sequence",
    "to_ms2_pip",
    "from_ms2_pip",
    # Input protocol
    "HasSequence",
    # Batch
    "batch",
    "iter_batch",
    "diagnose",
    "BatchResult",
    "BatchOperation",
    "Diagnostic",
    # ProForma JSON
    "to_proforma_json",
    "from_proforma_json",
    "to_proforma_dict",
    "from_proforma_dict",
    "get_proforma_json_schema",
    "PROFORMA_JSON_SCHEMA_ID",
    "PROFORMA_JSON_SCHEMA_VERSION",
    # ProForma components
    "ChargedFormula",
    "FormulaElement",
    "GlycanComponent",
    "GlycanTag",
    "IsotopeReplacement",
    "GlobalChargeCarrier",
    "FixedModification",
    "PositionRule",
    "ModificationTags",
    "ModificationAmbiguousPrimary",
    "ModificationAmbiguousSecondary",
    "ModificationCrossLinker",
    "TagAccession",
    "TagCustom",
    "TagInfo",
    "TagMass",
    "TagName",
    "PositionScore",
    "PositionTag",
    "LimitTag",
    "ComkpTag",
    "ComupTag",
    "SequenceElement",
    "SequenceRegion",
    "Peptidoform",
    "PeptidoformIon",
    "CompoundPeptidoformIon",
    "CV",
    "Terminal",
    # errors
    "PeptacularError",
    "ProFormaFormatError",
    "UnknownModificationError",
    "UnknownEnzymeError",
    "UnknownElementError",
    "PeptacularKeyError",
    "CompositionError",
    "InvalidAdjustmentError",
    "InvalidPositionError",
    "UnsupportedOperationError",
    # parallel
    "ParallelMethod",
    "ParallelMethodLiteral",
    "set_start_method",
    "get_start_method",
    "get_available_start_methods",
    # physical constants
    "PROTON_MASS",
    "ELECTRON_MASS",
    "NEUTRON_MASS",
    "PROTON_CARRIER_MASS",
    "C13_NEUTRON_MASS",
    "PEPTIDE_AVERAGINE_NEUTRON_MASS",
]
